[workspace]
members = [
    "crates/cleaner-core",
    "crates/cleaner-tui",
]
default-members = ["crates/cleaner-tui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vyrti/cleaner"
homepage = "https://github.com/vyrti/cleaner"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3

[profile.release.build-override]
opt-level = 3
