[workspace]
members = [
    "crates/cleaner-core",
    "crates/cleaner-tui",
]
default-members = ["crates/cleaner-tui"]
resolver = "2"

[workspace.package]
version = "0.0.8"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3

[profile.release.build-override]
opt-level = 3
